name:                sparse-blob
version:             0.0.1
github:              "sourcedennis/haskell-sparse-blob"
license:             BSD3
author:              "Dennis Sprokholt"
maintainer:          "me@dennis.life"
copyright:           "2021 Dennis Sprokholt"

extra-source-files:
- README.md
- LICENSE

description:         Please see the README on GitHub at <https://github.com/sourcedennis/haskell-sparse-blob#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - bytestring >= 0.10 && < 0.11
  - containers >= 0.6 && < 0.7 # Only needed for SimpleBlob
  exposed-modules:
  - Data.SparseBlob

tests:
  sparse-blob-test:
    main:                Spec.hs
    source-dirs:
    - src
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers >= 0.6 && < 0.7
    - bytestring >= 0.10 && < 0.11
    - tasty >= 1.2.2 && < 1.4
    - tasty-hunit >= 0.10 && < 0.11
    - tasty-quickcheck >= 0.10 && < 0.11

benchmarks:
  sparse-blob-benchmarks:
    main:          Main.hs
    source-dirs:
    - src
    - benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers >= 0.6 && < 0.7
    - bytestring >= 0.10 && < 0.11
    - criterion >= 1.5 && < 1.6
